apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lie-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
  selector:
    matchLabels:
      app: "lie"